version: '3.8'

services:
  api:
    container_name: superpredict-api
    build:
      context: .
      dockerfile: Dockerfile-api
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT_API}
    command: node main.js
    environment:
      - NODE_ENV=production
      - PORT=${PORT_API}
      - REDIS_URL=${REDIS_URL}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
      - TWITTER_REDIRECT_URI=${TWITTER_REDIRECT_URI}
      - SESSION_ENCRYPTION_KEY=${SESSION_ENCRYPTION_KEY}
      - CLIENT_URL=${CLIENT_URL}
      - CRON_AUTH_KEY=${CRON_AUTH_KEY}

  client:
    container_name: superpredict-client
    build:
      context: .
      dockerfile: Dockerfile-client
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT_CLIENT}
    command: npx serve
    environment:
      - NODE_ENV=production
      - PORT=${PORT_CLIENT}
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api
