# Use an official Node.js runtime as a parent image
FROM node:20-alpine as build

# Install Python and build dependencies
RUN apk add --no-cache python3 make g++ linux-headers eudev-dev

# Set the working directory in the container
WORKDIR /app

RUN npm i -g serve

COPY dist/client .
# RUN npm install

# # Copy package.json and package-lock.json to the working directory
# COPY package*.json ./

# # Install app dependencies
# RUN npm install

# # Install serve globally - a static file serving utility
# RUN npm i -g serve

# # Copy the rest of your application code to the working directory
# COPY client/ .

# # Build the Vite app for production
# RUN npm run build-client

# # Set the working directory in the new image
# WORKDIR /app

# # Copy the build output from the previous stage
# # COPY --from=build /app/dist ./dist
# COPY client/ .

# Expose the port the app runs on
EXPOSE ${PORT_CLIENT}

# Start the server
# CMD ["serve", "-s", "dist"]